CREATE DATABASE carsharing;

CREATE TABLE user (
name VARCHAR(50) NOT NULL ,
lastname VARCHAR(50) NOT NULL ,
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
cp VARCHAR(10) NOT NULL ,
ville VARCHAR(50) NOT NULL ,
adresse VARCHAR(200) NOT NULL
) ENGINE = MYISAM ;